name: cars_equipments_shop
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  shared_preferences: ^2.3.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.14.0
  equatable: ^2.0.5
  cached_network_image: ^3.4.1
  awesome_snackbar_content: ^0.1.3
  image_picker: ^1.1.2
  iconsax: ^0.0.8
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  shimmer: ^3.0.0
  permission_handler: ^11.3.1
  flutter_localizations:
    sdk: flutter
  internet_connection_checker: ^2.0.0
  google_sign_in: ^6.2.1
  flex_color_picker: ^3.5.1
  flutter_3d_controller: ^1.3.1
  animated_text_kit: ^4.2.2
  intl: ^0.19.0
  lottie: ^3.1.2
  awesome_dialog: ^3.2.1
  url_launcher: ^6.3.0
  intl_phone_field: ^3.2.0
  dotted_border: ^2.1.0
  google_maps_flutter: ^2.9.0
  flutter_svg: ^2.0.10+1
  video_player: ^2.9.1
  flick_video_player: ^0.9.0
  firebase_app_check: ^0.2.1+8
  otp_text_field: ^1.1.3
  otp_text_field_v2: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lang/
    - assets/fonts/
    - assets/fonts/Poppins/
    - assets/fonts/Fustat/
    - assets/images/glb/
    - assets/images/png/
    - assets/images/jpg/
    - assets/images/svg/
    - assets/images/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
    - family: Fustat
      fonts:
        - asset: assets/fonts/Fustat/Fustat-Bold.ttf
        - asset: assets/fonts/Fustat/Fustat-ExtraBold.ttf
        - asset: assets/fonts/Fustat/Fustat-ExtraLight.ttf
        - asset: assets/fonts/Fustat/Fustat-Light.ttf
        - asset: assets/fonts/Fustat/Fustat-Medium.ttf
        - asset: assets/fonts/Fustat/Fustat-Regular.ttf
        - asset: assets/fonts/Fustat/Fustat-SemiBold.ttf