// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU0Uk5wuyylsUtFDFv59eHNg8K-yS-p0s',
    appId: '1:503744796100:web:5c1f8978bf4aeffa930091',
    messagingSenderId: '503744796100',
    projectId: 'cars-equipments-shop',
    authDomain: 'cars-equipments-shop.firebaseapp.com',
    storageBucket: 'cars-equipments-shop.appspot.com',
    measurementId: 'G-8L5ELHYXYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZKrPsG3u6nNvDwFmB0GdXPiz36iQPXZQ',
    appId: '1:503744796100:android:b97ae2c8cb05b267930091',
    messagingSenderId: '503744796100',
    projectId: 'cars-equipments-shop',
    storageBucket: 'cars-equipments-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4bSE7usXBdzlNq4mU7eZRj-cIkdqEz3A',
    appId: '1:503744796100:ios:f2d1ad99cedeb67a930091',
    messagingSenderId: '503744796100',
    projectId: 'cars-equipments-shop',
    storageBucket: 'cars-equipments-shop.appspot.com',
    iosBundleId: 'com.example.carsEquipmentsShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4bSE7usXBdzlNq4mU7eZRj-cIkdqEz3A',
    appId: '1:503744796100:ios:f2d1ad99cedeb67a930091',
    messagingSenderId: '503744796100',
    projectId: 'cars-equipments-shop',
    storageBucket: 'cars-equipments-shop.appspot.com',
    iosBundleId: 'com.example.carsEquipmentsShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU0Uk5wuyylsUtFDFv59eHNg8K-yS-p0s',
    appId: '1:503744796100:web:d7eb7d11010e3d6d930091',
    messagingSenderId: '503744796100',
    projectId: 'cars-equipments-shop',
    authDomain: 'cars-equipments-shop.firebaseapp.com',
    storageBucket: 'cars-equipments-shop.appspot.com',
    measurementId: 'G-RTJ99W4T8E',
  );
}
